# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: MySimpleLib - .NET Build, Test, Pack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  JF_URL: ${{ vars.JF_URL }}
  JF_APIKEY: ${{ secrets.JF_APIKEY }}
  JF_USERNAME: ${{ secrets.JF_USERNAME }}
  JF_PASSWORD: ${{ secrets.JF_PASSWORD }}

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: independent/SimpleSolution/SimpleSolution.MySimpleLib
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Pack
      run: dotnet pack --no-restore -o ./
    - name: Setup jFrog 
      run: dotnet nuget add source '$JF_URL' --name poc1-nuget-local --store-password-in-clear-text --username '$JF_USERNAME' --password $JF_PASSWORD
    - name: Push to jFrog 
      run: dotnet nuget push ./SimpleSolution.MySimpleLib.*.nupkg --source $JF_URL --api-key $JF_APIKEY
